# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Flutter action
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '1.22.x'
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: flutter pub get

      - name: Build
        run: flutter build apk
      
      - name: Upload APK
        uses: actions/upload-artifact@master
        with:
          name: apk-build
          path: build/app/outputs/apk/release
 
